spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/aetherterra_test
    username: aetherterra
    password: aetherterra
  flyway:
    clean-disabled: false
    clean-on-validation-error: true
  mail:
    host: localhost
    port: 1025
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

logging:
  level:
    com.aetherterra: INFO
    org.flywaydb: INFO
