spring:
  application:
    name: aetherterra-backend
  profiles:
    active: local
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

server:
  port: 8080
  error:
    include-message: on-param
